version: '3'

volumes:
  postgres_data: {}
  media_files: {}

services:

  database:
    image: postgres:alpine
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

  webapp:
    build: .
    command: sh /app/start.sh
    restart: unless-stopped
    depends_on:
      - database
    entrypoint: /app/entrypoint.sh
    env_file:
      - .env
    ports:
      - 8910:80
    volumes:
      - 'media_files:/app/assets/media'
