# Generated by Django 2.2 on 2019-04-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(upload_to='upload/images/')),
                ('document', models.FileField(upload_to='upload/files/')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
